import { Days } from "../types/slot.type";

export const HttpResponse = {
  OK: "OK",
  SERVER_ERROR: "internal server Error!",
  USER_EXIST: "User already exist",
  USER_CREATION_FAILED: "User Creation Failed",
  USER_NOT_FOUND: "User not Found",
  USER_BLOCKED: "User blocked",
  INVALID_CREDNTIALS: "Invalid Credentials",
  CREATED: "Created Successfully",
  LOGGED_IN_SUCCESSFULLY: "User Logged In Successfully",
  LOGGED_OUT: "User Logged Out",
  ACCESS_TOKEN_EXPIRED: "Access Token Expired",
  REFRESH_TOKEN_EXPIRED: "Refresh Token Expired",
  UNAUTHORIZED: "Unauthorized Access, Please Login First",
  TOKEN_NOT_FOUND: "Token not Found",
  ACCESS_DENIED: "Access Denied!",
  ITEM_EXIST: "Item Already Exist",
  INVALID_ID: `Invalid Id`,
  ITEM_NOT_FOUND: "Item not Found !",
  ORDER_EXIST: " You have already Purchased this Course !",
  FAILED_TO_CREATE_REVIE: "failed to add your review !",
  CHAT_NOT_FOUND: "Chat not found ",
  CHAT_ID_Required: "Chat id  required",
  NOT_PERMINTED: "Not permited to join this chat",
  COURSE_NOT_FOUND: "Course Not FOund",
  SLOT_EXIST: "A slot for the same course already exists.",
  BOOKING_EXIST: " You already Booked one Slot For This Course Review",
  BOOKING_TIME_CONFLICT: "You already have another session at this time",
  NO_BOOKED_SLOT: "We can't find your booked slot",
  NOT_STARTED:
    "The session has not started yet. Please wait until the start time.",
  SESSION_ENDED: "The session has already ended.",
  SLOT_EXIST_DAYS: (day: Days, existing: string) =>
    `You have already a slot on ${day} ${existing}`,
  SLOT_DATE: "You can only join on the scheduled date.",
  STRIPR_NOT_AVAILABLE: "Stripe Payment is not Available",
  SLOT_NOT_FOUND: "Your Slot not found",
  ORDER_ALREADY_EXIST: "Order Already Exist",
  ALREADY_PURCHASED: "You have already purchased the Course",
  SLOT_ALREADY_BOOKED: "This Slot Already Booked",
  CAN_NOT_CANCEL: "You can not Cancel the Booked Slot",
  TIME_EXCEEDED: "Sorry Cancellation not allowed within 12 hours",
  TRANSACTION_NOT_FOUND: "Transaction Not Found",
  NOT_ENROLLED: "Not enrolled",
};
