export enum DbModelName {
  AUTH_SESSION = "AuthSession",
  CATEGORY = "Category",
  CHAT = "Chat",
  COURSE = "Course",
  ENROLLMENT = "Enrollment",
  NOTIFICATION = "Notification",
  ORDER = "Order",
  REVIEW = "Review",
  SLOT_BOOKING = "SlotBooking",
  SLOT = "Slot",
  TRANSACTION = "Transaction",
  USER = "User",
  MESSAGE = "Message",
  CERTIFICATE = "Certificate",
  CHAT_BOT = "ChatBot",
}
